id = "Fir"
name = "Fir programming language"
version = "0.0.1"
schema_version = 1
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Fir programming language extension for Zed"
repository = "https://github.com/fir-lang/fir"

[grammars.fir]
repository = "https://github.com/fir-lang/tree-sitter-fir"
rev = "3a8851d27108f2b8de651a960ecfc308c36580cc"
