id = "Fir"
name = "Fir programming language"
version = "0.0.1"
schema_version = 1
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Fir programming language extension for Zed"
repository = "https://github.com/fir-lang/fir"

[grammars.fir]
repository = "https://github.com/fir-lang/tree-sitter-fir"
rev = "dd3eb5ec20dc456f4248b0cc5c5926352d59a01d"
