id = "Fir"
name = "Fir programming language"
version = "0.0.1"
schema_version = 1
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Fir programming language extension for Zed"
repository = "https://github.com/fir-lang/fir"

[grammars.fir]
repository = "https://github.com/fir-lang/tree-sitter-fir"
rev = "900ad3bf99393816d8d79e39563226bf2d73a204"
